name: 'mmr_counter'
version: 0.0.1
description: A web app built using angular.dart.
#author: Timur Munykin <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.9.0 <2.0.0'

dependencies:
  browser: ^0.10.0
  angular2: '2.0.0-beta.7'

transformers:
- angular2:
    entry_points:
      - web/index.dart
- $dart2js:
    minify: true
    checked: false
    commandLineOptions:
      - --enable-experimental-mirrors
      - --suppress-warnings
      - --suppress-hints
      - --disable-type-inference
      - --trust-primitives
      - --trust-type-annotations
